name: Conformance

on: [pull_request]

jobs:
  formatting:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v2

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.13.0

      - name: Run reviewdog (gofmt)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gofmt -s -d . | reviewdog -name="gofmt" -f=diff -f.diff.strip=0 -reporter=github-pr-review

      #- name: Run reviewdog
      #  env:
      #    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
      #  run: |
      #    gofmt -s -d . | reviewdog -name="gofmt" -f=diff -f.diff.strip=0 --diff="git diff FETCH_HEAD"

      #- name: Check gofmt
      #  run: |
      #    test -z "$(gofmt -l .)" || gofmt -l . && exit 1
