name: Format the code

on: [pull_request]

jobs:
  format:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run gofmt
        run: gofmt -w -s .

      - name: Run reviewdog (github-pr-suggest)
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
