name: Check gofmt

on: [pull_request]

jobs:
  gofmt:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt
