name: Vetting

on: [pull_request]

jobs:
  gofmt:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog (github-pr-check)
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet -fail-on-error
