name: Vet the code

on: [pull_request]

jobs:
  vet:
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for go.mod
        run: test -f go.mod

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run go vet
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go vet $(go list ./... | grep -v /vendor/) | reviewdog -f=govet -reporter=github-pr-check

      #- name: Run reviewdog (github-pr-check)
      #  env:
      #    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
        #  reviewdog -reporter=github-pr-check -runners=govet -fail-on-error
